/*
  This file is automatically generated. Any changes will be overwritten.
  Modify edit-member.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { LabelComponent } from '@radzen/angular/dist/label';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { DatePickerComponent } from '@radzen/angular/dist/datepicker';
import { EmailValidatorComponent } from '@radzen/angular/dist/email-validator';
import { FileInputComponent } from '@radzen/angular/dist/file-input';

import { ConfigService } from '../config.service';

import { ConDataService } from '../con-data.service';
import { SecurityService } from '../security.service';

export class EditMemberGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('closeLabel') closeLabel: LabelComponent;
  @ViewChild('closeButton') closeButton: ButtonComponent;
  @ViewChild('label0') label0: LabelComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('firstNameLabel') firstNameLabel: LabelComponent;
  @ViewChild('firstName') firstName: TextBoxComponent;
  @ViewChild('firstNameRequiredValidator') firstNameRequiredValidator: RequiredValidatorComponent;
  @ViewChild('middleNameLabel') middleNameLabel: LabelComponent;
  @ViewChild('middleName') middleName: TextBoxComponent;
  @ViewChild('surnameLabel') surnameLabel: LabelComponent;
  @ViewChild('surname') surname: TextBoxComponent;
  @ViewChild('surnameRequiredValidator') surnameRequiredValidator: RequiredValidatorComponent;
  @ViewChild('genderIdLabel') genderIdLabel: LabelComponent;
  @ViewChild('genderId') genderId: DropDownComponent;
  @ViewChild('genderIdRequiredValidator') genderIdRequiredValidator: RequiredValidatorComponent;
  @ViewChild('dateOfBirthLabel') dateOfBirthLabel: LabelComponent;
  @ViewChild('dateOfBirth') dateOfBirth: DatePickerComponent;
  @ViewChild('residentialAddressLabel') residentialAddressLabel: LabelComponent;
  @ViewChild('residentialAddress') residentialAddress: TextBoxComponent;
  @ViewChild('residentialAddressRequiredValidator') residentialAddressRequiredValidator: RequiredValidatorComponent;
  @ViewChild('officeAddressLabel') officeAddressLabel: LabelComponent;
  @ViewChild('officeAddress') officeAddress: TextBoxComponent;
  @ViewChild('mobileNumber1Label') mobileNumber1Label: LabelComponent;
  @ViewChild('mobileNumber1') mobileNumber1: TextBoxComponent;
  @ViewChild('mobileNumber1RequiredValidator') mobileNumber1RequiredValidator: RequiredValidatorComponent;
  @ViewChild('whatsappNumberLabel') whatsappNumberLabel: LabelComponent;
  @ViewChild('whatsappNumber') whatsappNumber: TextBoxComponent;
  @ViewChild('emailLabel') emailLabel: LabelComponent;
  @ViewChild('email') email: TextBoxComponent;
  @ViewChild('emailValidator0') emailValidator0: EmailValidatorComponent;
  @ViewChild('memberPhotoLabel') memberPhotoLabel: LabelComponent;
  @ViewChild('memberPhoto') memberPhoto: FileInputComponent;
  @ViewChild('currentPositionIdLabel') currentPositionIdLabel: LabelComponent;
  @ViewChild('currentPositionId') currentPositionId: DropDownComponent;
  @ViewChild('button3') button3: ButtonComponent;
  @ViewChild('button4') button4: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  conData: ConDataService;

  security: SecurityService;
  hasChanges: any;
  canEdit: any;
  member: any;
  getGendersResult: any;
  getMemberPositionsResult: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.conData = this.injector.get(ConDataService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.hasChanges = false;

    this.canEdit = true;

    this.conData.getMemberByMemberId(null, this.parameters.MemberID)
    .subscribe((result: any) => {
      this.member = result;
    }, (result: any) => {
      this.canEdit = !(result.status == 400);
    });

    this.conData.getGenders(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getGendersResult = result.value;
    }, (result: any) => {

    });

    this.conData.getMemberPositions(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getMemberPositionsResult = result.value;
    }, (result: any) => {

    });
  }

  closeButtonClick(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }

  button0Click(event: any) {
    this.load()
  }

  form0Submit(event: any) {
    this.conData.updateMember(null, this.parameters.MemberID, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.hasChanges = result.status == 412;

      this.canEdit = !(result.status == 400);

      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to update Member` });
    });
  }

  button4Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
